name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # permissions:
#      packages: write
    runs-on: ubuntu-latest
    name: CI Build

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test (inc Code Coverage)
      run: dotnet test --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage > ./test-results.txt

    - name: Prettify Test Results
      run: |
        echo "<details><summary>Test Results</summary>" > ./test-results.md
        cat ./test-results.txt >> ./test-results.md
        echo "</details>" >> ./test-results.md
        cat ./test-results.md >> $GITHUB_STEP_SUMMARY

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Prepare Artifacts
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/pr-number
        cat test-results.md > ./pr/test-results.md
        cat code-coverage-results.md > ./pr/code-coverage-results.md

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: pr
        path: pr/

    # - name: Connect to Cygnus packages in GitHub
    #   run: dotnet nuget add source --username medstar117 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/medstar117/index.json"

    # - name: Publish
    #   run: dotnet nuget push **/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
    